parameters:
    cocorico_experiment.experiment_img_xsmall_w: 90
    cocorico_experiment.experiment_img_xsmall_h: 67
    cocorico_experiment.experiment_img_small_w: 100
    cocorico_experiment.experiment_img_small_h: 75
    cocorico_experiment.experiment_img_xxmedium_w: 150
    cocorico_experiment.experiment_img_xxmedium_h: 112
    cocorico_experiment.experiment_img_xmedium_w: 200
    cocorico_experiment.experiment_img_xmedium_h: 150
    cocorico_experiment.experiment_img_medium_w: 275
    cocorico_experiment.experiment_img_medium_h: 206
    cocorico_experiment.experiment_img_large_w: 384
    cocorico_experiment.experiment_img_large_h: 288
    cocorico_experiment.experiment_img_xlarge_w: 527
    cocorico_experiment.experiment_img_xlarge_h: 395
    cocorico_experiment.experiment_img_xxlarge_w: 680
    cocorico_experiment.experiment_img_xxlarge_h: 510
    cocorico_experiment.experiment_img_max_upload_size: 12
    cocorico_experiment.experiment_img_preview_w: 275
    cocorico_experiment.experiment_img_preview_h: 206
