cocorico_experiment_frontend:
    resource: "@CocoricoExperimentBundle/Controller/Frontend"
    type:     annotation

cocorico_experiment_dashboard:
    resource: "@CocoricoExperimentBundle/Controller/Dashboard"
    type:     annotation
    prefix: /dashboard

cocorico_experiment_api:
    resource: "@CocoricoExperimentBundle/ApiController"
    type: annotation
    prefix: /api
    options: {i18n: false}
