services:
    sonata.admin.recover:
        class: Cocorico\BalanceBundle\Admin\RecoverAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Recovers", label_catalogue: "cocorico_admin_menu" }
        arguments:
            - ~
            - Cocorico\BalanceBundle\Entity\BalanceMovement
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setCurrency, ["%cocorico.currency%"]]
