services:
    cocorico_balance.form.handler.credit:
        class: Cocorico\BalanceBundle\Form\Handler\Dashboard\CreditFormHandler
        arguments:
            - "@request_stack"
            - "@security.token_storage"
            - "@cocorico_balance.manager.credit"

    cocorico_mangopay.form.handler.credit_card:
        class: Cocorico\BalanceBundle\Form\Handler\Dashboard\CreditCardFormHandler
        arguments:
            - "@session"
            - "@request_stack"
            - "@router"
            - "@translator.default"
            - "@cocorico_balance.manager.credit"
            - "@cocorico_mangopay.card_registration_manager"
            - "@labtoo_mangopay.pay_in_card_manager"

    cocorico_mangopay.form.handler.credit_card_validation:
        class: Cocorico\BalanceBundle\Form\Handler\Dashboard\CreditCardValidationFormHandler
        arguments:
            - "@session"
            - "@request_stack"
            - "@router"
            - "@translator.default"
            - "@cocorico_balance.manager.credit"
            - "@labtoo_mangopay.pay_in_card_manager"

    cocorico_balance.form.handler.debit:
        class: Cocorico\BalanceBundle\Form\Handler\Frontend\DebitFormHandler
        arguments:
            - "@event_dispatcher"
            - "@cocorico.booking.manager"
            - "@cocorico_balance.manager.transaction"
            - "@request_stack"

    cocorico_balance.form.handler.recover:
        class: Cocorico\BalanceBundle\Form\Handler\Dashboard\RecoverFormHandler
        arguments:
            - "@request_stack"
            - "@security.token_storage"
            - "@cocorico_balance.manager.recover"

    cocorico_balance.form.handler.recover_check:
        class: Cocorico\BalanceBundle\Form\Handler\Dashboard\RecoverCheckFormHandler
        arguments:
            - "@request_stack"
            - "@security.token_storage"
            - "@cocorico_balance.manager.recover"
