services:
    cocorico_balance.manager.credit:
        class: Cocorico\BalanceBundle\Manager\CreditManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@labtoo_mangopay.pay_in_card_manager"
            - "@labtoo_mangopay.pay_in_bank_wire_manager"

    cocorico_balance.manager.recover:
        class: Cocorico\BalanceBundle\Manager\RecoverManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@cocorico_mangopay.bank_account_manager"
            - "@cocorico_mangopay.user_manager"
            - "@monolog.logger"
            - "@cocorico.mailer.twig_swift"
            - parameters:
                recover_delay: "%cocorico_balance.recover_delay%"
                bankwire_checking_simulation: "%cocorico.bankwire_checking_simulation%"

    cocorico_balance.manager.transaction:
        class: Cocorico\BalanceBundle\Manager\TransactionManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@cocorico_mangopay.transfer_manager"
