services:
    labtoo_mangopay.pay_in_bank_wire_manager:
        class: Labtoo\MangoPayBundle\Model\Manager\PayInBankWireManager
        arguments:
            - "@labtoo_mangopay.pay_in_bank_wire_request"
            - "%cocorico.currency%"

    labtoo_mangopay.pay_in_card_manager:
        class: Labtoo\MangoPayBundle\Model\Manager\PayInCardManager
        arguments:
            - "@labtoo_mangopay.pay_in_card_request"
            - "%cocorico.currency%"

    labtoo_mangopay.pay_out_bank_wire_manager:
        class: Labtoo\MangoPayBundle\Model\Manager\PayOutBankWireManager
        arguments:
            - "@labtoo_mangopay.pay_out_bank_wire_request"
            - "%cocorico.currency%"

    labtoo_mangopay.user_manager:
        class: Labtoo\MangoPayBundle\Model\Manager\UserManager
        arguments:
            - "@cocorico_mangopay.user_request"
