services:

    sonata.admin.experiment:
        class: Cocorico\ExperimentBundle\Admin\ExperimentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Listings",  label: "Experiments Management", label_catalogue: "cocorico_admin_menu" }
        arguments:
            - ~
            - Cocorico\ExperimentBundle\Entity\Experiment
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
            - [ setTemplate, [edit, CocoricoExperimentBundle:Admin\Experiment:edit.html.twig]]
            - [ setLocale, ["%cocorico.locale%"]]
            - [ setLocales, ["%cocorico.locales%"]]
            - [ setExperimentManager, ["@cocorico_experiment.manager.experiment"]]

    sonata.admin.experiment_search:
        class: Cocorico\ExperimentBundle\Admin\ExperimentSearchAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Elasticsearch",  label: "History", label_catalogue: "cocorico_admin_menu" }
        arguments:
            - ~
            - Cocorico\ExperimentBundle\Entity\ExperimentSearch
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
